export const SET_LOCATION_FILTER = 'SET_LOCATION_FILTER';
export const SET_WEBSITE_FILTER = 'SET_WEBSITE_FILTER';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
export const SET_ERROR_INFO = 'SET_ERROR_INFO';
export const RESET_ERROR_INFO = 'RESET_ERROR_INFO';

