spring:
  profiles:
      active: ${ACTIVE_PROFILE}

  application:
    name: scraper-service

  data:
    mongodb:
      auto-index-creation: true
  lifecycle:
    timeout-per-shutdown-phase: 40s
server:
  shutdown: graceful
